#!/bin/sh

MODULE_NAME='rstorage'
MODULE_CATEGORY='service'
PLUGIN_LIST=`uci get lafite.main.plugins`

isExist=0
for name in $PLUGIN_LIST
do
    [[ ${name} == ${MODULE_NAME} ]] && isExist=1
done

[[ $isExist == 0 ]] && \
uci batch <<-EOF
    add_list lafite.main.plugins=${MODULE_NAME}
    set lafite.${MODULE_NAME}='plugin'
    set lafite.${MODULE_NAME}.category=${MODULE_CATEGORY}
    commit lafite
EOF

uci batch <<-EOF
    set lafite.${MODULE_NAME}.version='1.0.1'
    set lafite.${MODULE_NAME}.release='14'
    set lafite.${MODULE_NAME}.hashcode='1082cbd9db861fbf79f90abe586a16b18aa0c02b'
    set lafite.${MODULE_NAME}.description='Display Extra Device Plugin for Lafite Theme by Ray Config'
    commit lafite
EOF

uci batch <<-EOF
   set lafite.${MODULE_NAME}.jspath='/luci-static/lafite/js/rstorage-218991f7ee.js'
   commit lafite
EOF

exit 0
