#!/bin/sh

MODULE_NAME='rauth'
MODULE_CATEGORY='auth'
PLUGIN_LIST=`uci get lafite.main.plugins`

isExist=0
for name in $PLUGIN_LIST
do
    [[ ${name} == ${MODULE_NAME} ]] && isExist=1
done

[[ $isExist == 0 ]] && \
uci batch <<-EOF
    add_list lafite.main.plugins=${MODULE_NAME}
    set lafite.${MODULE_NAME}='plugin'
    set lafite.${MODULE_NAME}.category=${MODULE_CATEGORY}
    commit lafite
EOF

[[ $isExist == 0 ]] && \
uci batch <<-EOF
    set lafite.${MODULE_NAME}.enabled='1'
    commit lafite
EOF

uci batch <<-EOF
    set lafite.${MODULE_NAME}.version='1.0.1'
    set lafite.${MODULE_NAME}.release='25'
    set lafite.${MODULE_NAME}.hashcode='a5db0e2802975b6e218e109f2d5e8018700a3814'
    set lafite.${MODULE_NAME}.description='Auth Plugin for Lafite Theme by Ray Config'
    commit lafite
EOF

uci batch <<-EOF
   set lafite.${MODULE_NAME}.jspath='/luci-static/lafite/js/rauth-a06bfd783a.js'
   commit lafite
EOF

exit 0
