#!/bin/sh

MODULE_NAME='roverview'
MODULE_CATEGORY='overview'
PLUGIN_LIST=`uci get lafite.main.plugins`

isExist=0
for name in $PLUGIN_LIST
do
    [[ ${name} == ${MODULE_NAME} ]] && isExist=1
done

[[ $isExist == 0 ]] && \
uci batch <<-EOF
    add_list lafite.main.plugins=${MODULE_NAME}
    set lafite.${MODULE_NAME}='plugin'
    set lafite.${MODULE_NAME}.category=${MODULE_CATEGORY}
    commit lafite
EOF

[[ $isExist == 0 ]] && \
uci batch <<-EOF
    set lafite.${MODULE_NAME}.enabled='1'
    commit lafite
EOF

uci batch <<-EOF
    set lafite.${MODULE_NAME}.version='1.0.1'
    set lafite.${MODULE_NAME}.release='75'
    set lafite.${MODULE_NAME}.hashcode='eca0b9b3e37001c8e4d897659e1af9578a57aa39'
    set lafite.${MODULE_NAME}.description='Overview Route Status Plugin for Lafite Them by Ray Confige'
    commit lafite
EOF

uci batch <<-EOF
   delete lafite.${MODULE_NAME}.commons
   add_list lafite.${MODULE_NAME}.commons='clientlist'
   add_list lafite.${MODULE_NAME}.commons='bandwidth'

   commit lafite
EOF

uci batch <<-EOF
   set lafite.${MODULE_NAME}.jspath='/luci-static/lafite/js/roverview-7716a8bf11.js'
   commit lafite
EOF

exit 0
