#!/bin/sh

MODULE_NAME='rsecurity'
MODULE_CATEGORY='setting'
PLUGIN_LIST=`uci get lafite.main.plugins`

isExist=0
for name in $PLUGIN_LIST
do
    [[ ${name} == ${MODULE_NAME} ]] && isExist=1
done

[[ $isExist == 0 ]] && \
uci batch <<-EOF
    add_list lafite.main.plugins=${MODULE_NAME}
    set lafite.${MODULE_NAME}='plugin'
    set lafite.${MODULE_NAME}.category=${MODULE_CATEGORY}
    commit lafite
EOF

uci batch <<-EOF
    set lafite.${MODULE_NAME}.version='1.0.1'
    set lafite.${MODULE_NAME}.release='59'
    set lafite.${MODULE_NAME}.hashcode='d63c23d9790845593f6623348ede43df3a7fdd05'
    set lafite.${MODULE_NAME}.description='Security Page for Lafite Theme by Ray Config'
    commit lafite
EOF

uci batch <<-EOF
   set lafite.${MODULE_NAME}.jspath='/luci-static/lafite/js/rsecurity-62f72098c0.js'
   commit lafite
EOF

exit 0
