#
# Copyright (C) 2016-2017 PandoraBox Team
#
include $(TOPDIR)/rules.mk
LUCI_TITLE:=LuCI lafite theme
LUCI_DEPENDS:=+luci-mod-pandorabox
include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
