#!/bin/sh

MODULE_NAME='installed'
MODULE_CATEGORY='service'
PLUGIN_LIST=`uci get lafite.main.plugins`

isExist=0
for name in $PLUGIN_LIST
do
    [[ ${name} == ${MODULE_NAME} ]] && isExist=1
done

[[ $isExist == 0 ]] && \
uci batch <<-EOF
    add_list lafite.main.plugins=${MODULE_NAME}
    set lafite.${MODULE_NAME}='plugin'
    set lafite.${MODULE_NAME}.category=${MODULE_CATEGORY}
    commit lafite
EOF

uci batch <<-EOF
    set lafite.${MODULE_NAME}.version='1.0.1'
    set lafite.${MODULE_NAME}.release='13'
    set lafite.${MODULE_NAME}.hashcode='a6f4e7136f27f8ea64e779aaade8815f40e8f6ff'
    set lafite.${MODULE_NAME}.description='Display Installed Plugin for Lafite Theme by Ray Config'
    commit lafite
EOF

uci batch <<-EOF
   set lafite.${MODULE_NAME}.jspath='/luci-static/lafite/js/installed-5ca73502cf.js'
   commit lafite
EOF

exit 0
