#!/bin/sh

MODULE_NAME='rmodulestore'
MODULE_CATEGORY='service'
PLUGIN_LIST=`uci get lafite.main.plugins`

isExist=0
for name in $PLUGIN_LIST
do
    [[ ${name} == ${MODULE_NAME} ]] && isExist=1
done

[[ $isExist == 0 ]] && \
uci batch <<-EOF
    add_list lafite.main.plugins=${MODULE_NAME}
    set lafite.${MODULE_NAME}='plugin'
    set lafite.${MODULE_NAME}.category=${MODULE_CATEGORY}
    commit lafite
EOF

uci batch <<-EOF
    set lafite.${MODULE_NAME}.version='1.0.1'
    set lafite.${MODULE_NAME}.release='2'
    set lafite.${MODULE_NAME}.hashcode='1c2997c3299eec6cb07cc37fb6a7f1a613a12f76'
    set lafite.${MODULE_NAME}.description='Module Store for Lafite Theme by Ray Config'
    commit lafite
EOF

uci batch <<-EOF
   set lafite.${MODULE_NAME}.jspath='/luci-static/lafite/js/rmodulestore-b3f287910a.js'
   commit lafite
EOF

exit 0
