#!/bin/sh

MODULE_NAME='rwan'
MODULE_CATEGORY='interface'
PLUGIN_LIST=`uci get lafite.main.plugins`

isExist=0
for name in $PLUGIN_LIST
do
    [[ ${name} == ${MODULE_NAME} ]] && isExist=1
done

[[ $isExist == 0 ]] && \
uci batch <<-EOF
    add_list lafite.main.plugins=${MODULE_NAME}
    set lafite.${MODULE_NAME}='plugin'
    set lafite.${MODULE_NAME}.category=${MODULE_CATEGORY}
    commit lafite
EOF

uci batch <<-EOF
    set lafite.${MODULE_NAME}.version=1.0.1
    set lafite.${MODULE_NAME}.release=70
    set lafite.${MODULE_NAME}.hashcode=319036dac078968286d077e6f37864329ea282b7
    set lafite.${MODULE_NAME}.description=WAN Page for Lafite Theme by Ray Config
    commit lafite
EOF

uci batch <<-EOF
   delete lafite.${MODULE_NAME}.commons
   add_list lafite.${MODULE_NAME}.commons='wan'

   commit lafite
EOF

uci batch <<-EOF
   set lafite.${MODULE_NAME}.jspath='/luci-static/lafite/js/rwan-6a3d6581bf.js'
   commit lafite
EOF

exit 0
