#!/bin/sh

MODULE_NAME='wireless_relay'
MODULE_CATEGORY='service'
PLUGIN_LIST=`uci get lafite.main.plugins`

isExist=0
for name in $PLUGIN_LIST
do
    [[ ${name} == ${MODULE_NAME} ]] && isExist=1
done

[[ $isExist == 0 ]] && \
uci batch <<-EOF
    add_list lafite.main.plugins=${MODULE_NAME}
    set lafite.${MODULE_NAME}='plugin'
    set lafite.${MODULE_NAME}.category=${MODULE_CATEGORY}
    commit lafite
EOF


[[ $isExist == 0 ]] && \
uci batch <<-EOF
    add firewall zone
    add_list firewall.@zone[-1].network='wan'
    add_list firewall.@zone[-1].network='wan6'
    add_list firewall.@zone[-1].network='wwan'
    set firewall.@zone[-1].name='wan'
    set firewall.@zone[-1].input='REJECT'
    set firewall.@zone[-1].output='ACCEPT'
    set firewall.@zone[-1].forward='REJECT'
    set firewall.@zone[-1].masq='1'
    set firewall.@zone[-1].mtu_fix='1'
    commit firewall
    set network.wwan=interface
    set network.wwan.proto='dhcp'
    commit network
EOF

uci batch <<-EOF
   set lafite.${MODULE_NAME}.jspath='/luci-static/lafite/js/wireless_relay-945d8a40a8.js'
   commit lafite
EOF

exit 0
